apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kitchen-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "kitchen-api"
        static_configs:
          - targets: ["kitchen-api:3000"]