name: Kitchen App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: api
        run: npm install

      - name: Run lint
        working-directory: api
        run: npm run lint

      - name: Run tests
        working-directory: api
        run: npm test

      - name: Build Docker image
        run: docker build -t kitchen-api:ci ./api